<?php $comment = $this->getBillingComment(); ?>
<div class="col2-set order-info-box">
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('Billing Comment:')?></h2>
            </div>
            <div class="box-content">
                <h5><?php echo $comment->getSubjComment();?></h5>
                <p><?php echo $comment->getComment();?></p>
            </div>
        </div>
    </div>
</div>

