<?php if($this->getCheckout()->getStepData('billing_comment', 'complete')): ?>
    <dt class="complete">
        <?php echo $this->__('Billing Comment') ?> <span class="separator">|</span> <a href="#deliverydate" onclick="checkout.accordion.openSection('opc-billing_comment'); return false;"><?php echo $this->__('Change') ?></a>
    </dt>
    <dd class="complete">
        <div>
            <?php echo $this->__('Billing Subject Comment: ');?>
            <?php
            $subComment = $this->getQuote()->getSubjectComment();
            echo $subComment;
            ?>
        </div>
    </dd>
<?php else: ?>
    <dt>
        <?php echo $this->__('Billing Comment') ?>
    </dt>
<?php endif; ?>